# Generated by Django 5.1.7 on 2025-03-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
